### ISSUE TITLE
Read ME Not Available

### ISSUE THREAD

**Issue by LamaBimal** [zapimoveis/aws-copy-large-files-s3#5]
I am not getting any ReadME File for further use.

**Comment by shikow-laroye** [comment]
@LamaBimal Hi! Do you need how to use?

**Comment by LamaBimal** [comment]
> @LamaBimal Hi! Do you need how to use?

yes. Could you please provide some information.

**Comment by marcieltorres** [comment]
@LamaBimal so, this project works as a `snippet` (or something like that :eyes: ). You can copy the file `https://github.com/zapimoveis/aws-copy-large-files-s3/blob/master/source/lib/index.js` and use in your project (we are using only `aws-sdk` dependency).
